<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>97483196-e3f5-4508-b1a9-6964ab9a87bf</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="OpenTelemetry.Api" Version="1.9.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.OpenTelemetry" Version="4.2.0" />
    <PackageReference Include="Serilog.Sinks.Seq" Version="9.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\contract\TrueLogs.Contract.Emitter\TrueLogs.Contract.Emitter.csproj" />
    <ProjectReference Include="..\..\contract\TrueLogs.Contract.Web\TrueLogs.Contract.Web.csproj" />
    <ProjectReference Include="..\..\emitter\adapter\TrueLogs.Emitter.Adapter.File\TrueLogs.Emitter.Adapter.File.csproj" />
    <ProjectReference Include="..\..\emitter\TrueLogs.Emitter.Client\TrueLogs.Emitter.Client.csproj" />
    <ProjectReference Include="..\..\storage\TrueLogs.Storage.LiteDB\TrueLogs.Storage.LiteDB.csproj" />
    <ProjectReference Include="..\..\storage\TrueLogs.Storage\TrueLogs.Storage.csproj" />
    <ProjectReference Include="..\..\aspire\TrueLogs.ServiceDefaults\TrueLogs.ServiceDefaults.csproj" />
    <ProjectReference Include="..\TrueLogs.Api.Core\TrueLogs.Api.Core.csproj" />
  </ItemGroup>

</Project>
